version: '3.8'

services:
  # ==========================================
  # MongoDB - Primary Database
  # ==========================================
  mongodb:
    image: mongo:6.0
    container_name: buy01-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - buy01-network

  # ==========================================
  # Zookeeper - Required for Kafka
  # ==========================================
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: buy01-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - buy01-network

  # ==========================================
  # Kafka - Event-Driven Message Broker
  # ==========================================
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: buy01-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - buy01-network

  # ==========================================
  # Mongo Express (Optional UI for your DB)
  # ==========================================
  mongo-express:
    image: mongo-express:1.0.2
    container_name: buy01-mongo-express
    restart: unless-stopped
    ports:
      - "8085:8081"
    environment:
      # 1. Credentials for the Browser UI login pop-up
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER_CONFIG}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD_CONFIG}

      # 2. The single connection string required by v1.0.2+
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD_URL_ENCODED}@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb
    networks:
      - buy01-network
  product-service:
    build: ./backend/product-service
    container_name: buy01-product-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${DB_USER}:${DB_PASSWORD_URL_ENCODED}@mongodb:27017/product_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - buy01-network
  user-service:
    build: ./backend/user-service
    container_name: buy01-user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${DB_USER}:${DB_PASSWORD_URL_ENCODED}@mongodb:27017/user_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - buy01-network
  media-service:
    build: ./backend/media-service
    container_name: buy01-media-service
    ports:
      - "8082:8082"
    environment:
      # environment:
      SPRING_DATA_MONGODB_URI: mongodb://${DB_USER}:${DB_PASSWORD_URL_ENCODED}@mongodb:27017/media_db?authSource=admin
      CLOUDINARY_CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${API_KEY}
      CLOUDINARY_API_SECRET: ${API_SECRET}
    depends_on:
      - mongodb
    networks:
      - buy01-network
  discovery-service:
    build: ./backend/discovery-server
    container_name: buy01-discovery-service
    ports:
      - "8083:8083"
    environment:
      # environment:
      SPRING_DATA_MONGODB_URI: mongodb://${DB_USER}:${DB_PASSWORD_URL_ENCODED}@mongodb:27017/media_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - buy01-network
  api-gateway:
    build: ./backend/api-gateway-service
    container_name: buy01-api-gateway-service
    ports:
      - "8084:8084"
    environment:
      # environment:
      SPRING_DATA_MONGODB_URI: mongodb://${DB_USER}:${DB_PASSWORD_URL_ENCODED}@mongodb:27017/media_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - buy01-network
# Define persistent storage and networking
volumes:
  mongo-data:

networks:
  buy01-network:
    driver: bridge
