sonar.projectKey=buy-01
sonar.projectName=buy-01
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/vendor/**,**/target/**,**/*.min.js,**/generated/**

sonar.tests=.
sonar.test.inclusions=**/*test*,**/*spec*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.php.coverage.reportPaths=coverage.xml

sonar.host.url=http://localhost:9000