server:
  port: 8088

spring:
  application:
    name: product-service
  data:
    mongodb:
       uri: ${SPRING_DATA_MONGODB_URI}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

media-service:
  base-url: ${MEDIA_SERVICE_BASE_URL}

springdoc:
  api-docs:
    path: /v3/api-docs